name: Deploy DB Infrastructure

on:
  push:
  workflow_dispatch:

jobs:
  tf-test:
    name: Terraform Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: 'us-east-1'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: 1.6.2
      
      - name: Prepare environment
        id: tf-init
        working-directory: src
        run: terraform init 

      - name: Terraform fmt
        id: tf-fmt        
        working-directory: src
        run: terraform fmt --recursive

      - name: Terraform validate
        id: tf-validate        
        working-directory: src
        run: terraform validate -no-color

      - name: Terraform Plan
        id: tf-plan        
        working-directory: src
        run: terraform plan -lock=false -no-color -input=false
        continue-on-error: true
  
  tf-deploy:
    name: Terraform Deploy

    needs: 
      - tf-test

    if: github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:          
          aws-region: 'us-east-1'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Prepare environment
        run: terraform init 

      - name: Terraform Plan
        run: terraform plan -lock=false -no-color -input=false

      - name: Execute terraform apply
        run: terraform apply -lock=false -auto-approve -input=false
