name: Deploy DB Infrastructure

on:
  push:
  workflow_dispatch:

jobs:
  tf-test:
    name: Terraform Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:          
          aws-region: 'us-east-1'
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt --recursive
        
      - name: Terraform Init
        id: init
        run: terraform init
        
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        continue-on-error: false

      - name: Terraform Plan
        id: plan
        run: terraform plan -lock=false -no-color -input=false
        continue-on-error: false
  
  tf-deploy:
    name: Terraform Deploy

    needs: 
      - tf-test

    if: github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:          
          aws-region: 'us-east-1'
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Prepare environment
        run: terraform init 

      - name: Terraform Plan
        run: terraform plan -lock=false -no-color -input=false

      - name: Execute terraform apply
        run: terraform apply -lock=false -auto-approve -input=false
